HAVET_ER_SKØNT = [
"Søgræs er altid grønnest",
"I naboens fiskedam",
"Du sir' du vil op på jorden",
"Men det er da synd og skam",
"Hernede i havets verden",
"Er alt det du holder af",
"Lykken for dig, her er den",
"Hvad mere vil du da ha'",
"Havet er skønt",
"Havet er skønt",
"Alle er kåde",
"Her i det våde",
"Alt er til pynt",
"Oppe på land er jobbet hårdt",
"Solen er varm, og livet kort",
"Her kan vi svømme, flyde og drømme",
"Havet er skønt",
"Og fiskene her er glade",
"Her plasker de nok så kækt",
"Deroppe bli'r fisk så flade",
"Og spræller når de bli'r stegt",
"De holder jer i akvarier",
"Ja det lyder helt barokt",
"Men det er kun for at bevar jer",
"Til den dag hvor i bli'r kogt",
"O nej!",
"Havet er skønt",
"Havet er skønt",
"Ingen bli'r slået",
"Renset og flået",
"Stoppet med grønt",
"Menneskene ser os kun som mad",
"Her er du fri og frisk og glad",
"Livsglæden bobler",
"Her mellem gopler",
"Havet er skønt",
"Havet er skønt",
"Havet er skønt",
"Her kan vi spille",
"Tralle og trille",
"Dejlig musik",
"Lyt til en rokke og en stør",
"De har det fineste gehør",
"Nyn melodien",
"Hør harmonien",
"Havet er skønt",
"En ål slår på stål",
"En sej tar' på vej",
"Makrel spiller selv",
"På gæller og skæl",
"En tun på basun",
"En laks spiller sax",
"En torsk driver dorsk i soul",
"En krebs bruger knibs",
"En sild bli'r helt vild",
"En spætte og helt",
"Har rytme og stil",
"En brisling tar fat",
"Med trat-tratte-rat",
"En trompetfisk gi'r et trut",
"Havet er skønt",
"Havet er skønt",
"Når en sej",
"Gubbigin the beguine",
"Er festen begyndt",
"Oppe på land er der kun sand",
"Mod os er de det rene vand",
"Østers som klemmer",
"Ofte de stemmer",
"Havet er skønt",
"Hver lille reje",
"Ta'r sin skalmeje",
"Havet er skønt",
"Hør vores snegle",
"To-tur til vejle",
"Det er blandt andet",
"Derfor er vandet",
"Det er så yndet",
"Bliv dog i dyndet",
"Havet er skønt"
]